// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6d_SUucQB5eJpaCTRPZMc0rXHcNvqoc',
    appId: '1:772916826036:web:0b615016b9db111d81ace1',
    messagingSenderId: '772916826036',
    projectId: 'crops-trace',
    authDomain: 'crops-trace.firebaseapp.com',
    storageBucket: 'crops-trace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwx-kDNgW40sr9qGVlagrHyLEM3pEvfGY',
    appId: '1:772916826036:android:d026c7593cbe12ee81ace1',
    messagingSenderId: '772916826036',
    projectId: 'crops-trace',
    storageBucket: 'crops-trace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWpm_3qSZN7uvmHflQJxXsyUkGOyj_9ow',
    appId: '1:772916826036:ios:ace6397d28fe5d5381ace1',
    messagingSenderId: '772916826036',
    projectId: 'crops-trace',
    storageBucket: 'crops-trace.appspot.com',
    iosBundleId: 'com.example.cropTraceability',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWpm_3qSZN7uvmHflQJxXsyUkGOyj_9ow',
    appId: '1:772916826036:ios:3cca2cf7cbfcebdc81ace1',
    messagingSenderId: '772916826036',
    projectId: 'crops-trace',
    storageBucket: 'crops-trace.appspot.com',
    iosBundleId: 'com.example.cropTraceability.RunnerTests',
  );
}
